version: '3.0'
services:
  web:
    restart: always
    image: jhonatangrymuza/magento2:1.0
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
    volumes:
      - ./dev:/var/www/html
    # build:
    #   context: .
    #   dockerfile: ./etc/docker/dockerfile_web
  db:
    image: mariadb:10
    container_name: mysql
    restart: always
    ports:
    - "3306:3306"
    volumes:
        - ./database/dump:/docker-entrypoint-initdb.d:rw
        - ./database/db80:/var/lib/mysql:rw
    env_file:
      - env
    command:
        'mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
volumes:
  db-data:
